version: '3.4' 
services:
  db:
    image: postgres
    ports:
      - "5432:5432"

#  stage-app:
#    image: wobbly-django

  app:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    image: wobbly-django
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=True
      - PRODUCTION=False
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432