version: '3.4'
services:
  wobbly-backend-service:
    build:
      context: ././
      dockerfile: deploy/Dockerfile
    image: wobbly-django
    command: ./docker-entrypoint.sh
    volumes:
      - ././:/code
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SECRET_KEY
      - DEBUG
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}